### ISSUE TITLE
Unhadled exception Error

### ISSUE THREAD

**Issue by RosalesSuperTech** [cfwprpht/PS4_AC1D_Flash-Tool#2]
I am receiving an unhandled exception error message with the below error, I am not sure how to troubleshoot this.

************* Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Log, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Log, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at PS4AC1DFlashTool.MAIN.buttonExtract_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by RosalesSuperTech** [comment]
Never Mind, I deleted the files from local machines and re-downloaded and issue was resolved.
